const products = [
    {
        '_id': '1',
        'name': "Nasco 32 inches NAS- J32FB Digital Satellite TV – HDMI - VGA - USB - Black",
        'image': 'https://gh.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/10/220799/1.jpg?5375',
        'description': "Entertainment will no longer be the same for you with a high visual quality and sound performance outside the norm. And you will have the ability to play the various contents from your USB drive without problems with the best qualities. It's HDMI connections replace the scart. They help convey both image and digital sound to enjoy a picture and sound in high definition. HDMI connectors are smaller than scart, but nevertheless are able to convey an image and better sound quality without interference or signal attenuation.",
        'brand':'Nasco',
        'category':'Electronics',
        'price': 1010.00,
        "countInStock": 10,
        'rating': 4.5,
        'numReviews': 2,
    },
    {
        '_id': '2',
        'name': "Guinness Malta Drink - 330ml x 6 Pet Bottles",
        'image': 'https://gh.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/56/746426/1.jpg?1327',
        'description': "It’s a carbonated malt soft drink called Malta Guinness. Much like beer, it’s brewed from barley and hops. Its rich dark brown color is similar to stout, but Malta is very sweet with molasses overtones. If you generally don’t drink soda, you might find Malta too syrupy for your taste. It helps to drink it ice cold, preferably with nice stack of ice cubes, which balances out the intense sweetness.",
        'brand':'Guinness',
        'category':'Beverages',
        'price': 36.87,
        "countInStock": 3,
        'rating': 4.5,
        'numReviews': 427,
    },
    {
        '_id': '3',
        'name': "Geisha Soap Germig Neem & Basil Soap -180g",
        'image': 'https://gh.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/75/391664/1.jpg?9103',
        'description': "extracts and finished with a mild, unreactive fragrance, the unmedicated soap deep cleans and nourishes the skin for a truly refreshing bath experience. The sweet-smelling soap bar is infused with glycerin and lanolin that act as natural moisturizing agents, revitalizing your skin and creating an attractive, healthy glow. Glycerin also moistens the skin, keeping it soft and supple, and helps build a protective layer that prevents drying and chapping. ",
        'brand':'Geisha',
        'category':'Health & Beauty',
        'price': 8.96,
        "countInStock": 0,
        'rating': 2.5,
        'numReviews': 5,
    },
    {
        '_id': '4',
        'name': "Round Neck Short Sleeve T-Shirt - 6 Pieces - Multicolour",
        'image': 'https://gh.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/12/346711/1.jpg?6004',
        'description': "Entertainment will no longer be the same for you with a high visual quality and sound performance outside the norm. And you will have the ability to play the various contents from your USB drive without problems with the best qualities. It's HDMI connections replace the scart. They help convey both image and digital sound to enjoy a picture and sound in high definition. HDMI connectors are smaller than scart, but nevertheless are able to convey an image and better sound quality without interference or signal attenuation.",
        'brand':'Adidas',
        'category':'Fashion',
        'price': 157.44,
        "countInStock": 5,
        'rating': 4.0,
        'numReviews': 1,
    },
    {
        '_id': '5',
        'name': "Backpack 3 In 1 Multi Functional School Business Backpack With USB Slot - Black",
        'image': 'https://gh.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/21/31487/1.jpg?6236',
        'description': "Entertainment will no longer be the same for you with a high visual quality and sound performance outside the norm. And you will have the ability to play the various contents from your USB drive without problems with the best qualities. It's HDMI connections replace the scart. They help convey both image and digital sound to enjoy a picture and sound in high definition. HDMI connectors are smaller than scart, but nevertheless are able to convey an image and better sound quality without interference or signal attenuation.",
        'brand':'',
        'category':'Backpacks',
        'price': 79.00,
        "countInStock": 16,
        'rating': 3.0,
        'numReviews': 38,
    }
]

export default products